version: '3'
services:
    back-office:
        image: 'node:alpine'
        restart: always
        ports:
            - '3000:3000'
        working_dir: /home/node
        volumes:
            - ./back-office:/home/node
            - /back-office/node_modules
        links:
            - api
        networks:
            - webappnetwork
        entrypoint: ['npm', 'start']

    api:
        image: 'node:12'
        env_file: .env
        restart: always
        ports:
            - '9000:9000'
        working_dir: /usr/src/app
        volumes:
            - ./API:/usr/src/app
            - /API/node_modules
        networks:
            - webappnetwork
        entrypoint: ['npm', 'start']

networks:
    webappnetwork:
        driver: bridge
